name: 'Build'

on:
  push:

jobs:
  deploy:
    name: 'Publish Docker image'
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Check Tag
        id: check-tag2
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - run: echo "::set-output name=dir::$(${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$)"
      - run: echo "::set-output name=dir::$(github.event.ref =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$)"
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: martijnhols/jetje
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=acceptance,enable=${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc') }}
            type=raw,value=acceptance,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
  
